### PR TITLE
Caves Update

### PR DESCRIPTION
**Pull request by sbtoonz**
I dont have friends to test this with but the mod loads ok

### CODE REVIEW

**Comment by sbtoonz** [comment]
I am awaiting feedback from some testers whom have friends to test with

**Comment by sbtoonz** [comment]
@projjm 
Tested against Caves update 
All works as expected 
Unable to reproduce any of the reports on nexus for item loss on trade cancel

**Comment by sbtoonz** [comment]
[PlayerTrading.zip](https://github.com/projjm/Valheim-Player-Trading/files/8364579/PlayerTrading.zip)

**Comment by projjm** [comment]
Thanks for updating this, I will update nexus/thunderstore with the updated files asap.

**Comment by sbtoonz** [comment]
> Thanks for updating this, I will update nexus/thunderstore with the updated files asap.

no worries :D some folks on the odin plus discord asked for this mod to be updated/ported and due to permissions on nexus my only solution was to make a PR for it :D

Glad you are still around to accept them

**Pull request merged**
